# Dependencies
##markdown:         redcarpet
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
permalink:        pretty
##relative_permalinks: true

# Setup
title:            Data<br>Thrust
tagline:          'Data Enthusiast Learning Resource'
description:      'Place where you can find the facts on various topics backed by data and extensive research along with the learning tutorials.'
url:              http://datathrust.github.io
baseurl:          /

author:
  name:           'Himanshu Aggarwal'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

## custom start
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

plugins: [jekyll-paginate]

paginate: 2
paginate_path: "page:num"
gems: [jekyll-gist]
## custom end

github:
  repo:           https://github.com/poole/hyde
