# Dependencies
##markdown:         redcarpet
highlighter:      pygments

kramdown:
  input: GFM

# Permalinks
##permalink:        pretty
permalink: /:categories/:title:output_ext
##relative_permalinks: true

# Setup
title:            'Data&#013Thrust'
tagline:          'Data Enthusiast Learning Resource'
description:      'Place where you can find the facts on various topics backed by data and extensive research along with the learning tutorials.'
baseurl:          "/"
url: "http://datathrust.in" # the base hostname & protocol for your site, e.g. http://example.com


github_username:  himanshu-aggarwal0909

author:
  name:           'Himanshu Aggarwal'
  url:            https://twitter.com/mdo

paginate:         2

# Custom vars
version:          2.1.0

## custom start
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

plugins: 
  - jekyll-paginate
  - github-pages

paginate: 2
paginate_path: "page:num"
gems: [jekyll-gist]
## custom end

github:
  repo:           https://github.com/himanshu-aggarwal0909/datathrust.github.io
